linux-hd: Remove PKG:{PN} which rename to existing package
ERROR: linux-hd-4.4.35-r0.9 do_package: package "kernel-base" is renamed to "kernel-base" using PKG:kernel-base, but package name already exists

https://git.openembedded.org/openembedded-core/commit/?id=f6cb63d3a871c4eef52d981131a56bf41aa1dcdf